### ISSUE TITLE
Ustawienia licznika

### ISSUE THREAD

**Issue by dmitriytim** [www005531/DTS-1946-4F#1]
Witam, czy mogę poprosić o step by step ustawienia licznika, może wideo już spróbowałem wszystkie protokóły. 
Nie wiem, jak ustawić na "8.1 none" - wyświetla na liczniku, że jest połączenie i znika.

`TypeError: Cannot read properties of undefined (reading 'subarray')`

`{"topic":"f74563b4626eba75","messageId":"637fa35aafde5db2add33cda","payload":"","error":"Error: Client Not Ready To Read At State init","_msgid":"77f6eae9baedc1b7"}`

**Comment by www005531** [comment]
Cześć,

prędkość transmisji i tryb komunikacji określa się wg schematu z instrukcji
użytkownika na stronie 14-tej - https://prnt.sc/swvNFfIW4EKX tj. przytrzymujesz enter, podajesz kod, enter, strzałką szukasz data, enter, masz 8.1. none i enter  i na koniec save Yes i enter..

Jeżeli to nie działa to znaczy, że coś może być nie tak z licznikiem.

Do przetestowania czy jest połączenie z licznikiem najlepiej użyć programu
Radzio Modbus Master Simulator http://en.radzio.dxp.pl/

Trzeba zacząć od wysłania polecenia ustawiającego adres - powinno być
zawsze przyjęte (na linii modbus musi być tylko jedno urządzenie bo to
polecenie zmienia wszystkim urządzeniom na linii adres na podany!).

Pozdrawiam,
Andrzej



czw., 24 lis 2022 o 18:05 dmitriytim ***@***.***> napisał(a):

**Comment by dmitriytim** [comment]
Witam 
Bardzo dziękuje, zmieniałem rs485, i nie zauważyłem, że B jest nie dobrze przylutowany,  przy testach w rękach na skanerach działało a przy   "Orange pi" - nie.  
Teraz działa
